version: '3.8'

services:
  zip-distance-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zip-distance-api
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - zip-distance-network

networks:
  zip-distance-network:
    driver: bridge

volumes:
  zipcodes-data:
    driver: local 